name: Register Package on Release

on:
  release:
    types: [published]

jobs:
  open-registrator-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue for JuliaRegistrator
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Register new release",
              body: "@JuliaRegistrator register"
            });